  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - org.acm::quarkus-lambda
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    QuarkusLambdaNativeFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: not.used.in.provided.runtime
        Runtime: provided
        CodeUri: build/function.zip
        MemorySize: 128
        Role: arn:aws:iam::190326285065:role/lambda-ex
        Timeout: 10
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
            QUARKUS_DATASOURCE_JDBC_URL: !Ref QUARKUS_DATASOURCE_JDBC_URL
            QUARKUS_DATASOURCE_REACTIVE_URL: !Ref QUARKUS_DATASOURCE_REACTIVE_URL
            QUARKUS_DATASOURCE_USERNAME: !Ref QUARKUS_DATASOURCE_USERNAME
            QUARKUS_DATASOURCE_PASSWORD: !Ref QUARKUS_DATASOURCE_PASSWORD
        Events:
          GetResource:
            Type: Api
            Properties:
              Path: /{proxy+}
              Method: any

  Parameters:
    QuarkusDatasourceJdbcUrl:
      Type: String
    QuarkusDatasourceReactiveUrl:
      Type: String
    QuarkusDatasourceUsername:
      Type: String
    QuarkusDatasourcePassword:
      Type: String

  Outputs:
    QuarkusLambdaNativeApi:
      Description: URL for application
      Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
      Export:
        Name: QuarkusLambdaNativeApi
